org.gradle.jvmargs=-Xmx2G
minecraft.version=1.8.9
loom.platform=forge
mod.version=3.0.1

group=at.yedel
mod.name=Antimations
mod.id=antimations
mod.description=Safe and customizable mod to cancel various gameplay animations
project.group=at.yedel
project.description=Safe and customizable mod to cancel various gameplay animations

oneconfigVersion=0.2.2-alpha+
oneconfigWrapperVersion=1.0.0-beta+
devAuthVersion=1.2.2