org.gradle.jvmargs=-Xmx2G
minecraft.version=1.8.9
loom.platform=forge
mod.version=2.2.1

group=at.yedel
mod.name=Antimations
mod.id=antimations
mod.description=Cancel swing and other animations on players
project.group=at.yedel
project.description=Cancel swing and other animations on players

oneconfigVersion=0.2.2-alpha+
oneconfigWrapperVersion=1.0.0-beta+
devAuthVersion=1.2.2