versions.fabricloader = "0.19.3"
versions.devauth = "1.2.2"

["1.8.9-forge"]
versioning = "single"
versions.oneconfig = "0.2.2-alpha+"
versions.oneconfigwrapper = "1.0.0-beta+"

["1.8.9-ornithe"]
versioning = "single"
versions.oneconfig = "1.1.12"
versions.oslcore = "0.10.0-alpha.5+mc14w27a-mc1.14.4"
versions.oslentrypoints = "0.6.1+mc13w16a-mc1.14.4"
versions.oslnetworking = "0.10.0-alpha.3+mc13w41a-mc18w30b"